CREATE DATABASE apple_retail_sales;
use apple_retail_sales;

-- STORES TABLE
CREATE TABLE stores(
    store_id VARCHAR(10) PRIMARY KEY,
    store_name VARCHAR(30),
    city VARCHAR(30),
    country VARCHAR(30)
);

-- CATEGORY TABLE
CREATE TABLE category(
    category_id VARCHAR(10) PRIMARY KEY,
    category_name VARCHAR(30)
);

-- PRODUCTS TABLE
CREATE TABLE products(
    product_id VARCHAR(10) PRIMARY KEY,
    product_name VARCHAR(35),
    category_id VARCHAR(10),
    launch_date DATE,
    price FLOAT,
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES category(category_id)
);

-- SALES TABLE
CREATE TABLE sales(
    sale_id VARCHAR(10) PRIMARY KEY,
    sale_date DATE,
    store_id VARCHAR(10),
    product_id VARCHAR(10),
    quantity INT,
    CONSTRAINT fk_store FOREIGN KEY (store_id) REFERENCES stores(store_id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- WARRANTY TABLE
CREATE TABLE warranty(
    claim_id VARCHAR(10) PRIMARY KEY,
    claim_date DATE,
    sale_id VARCHAR(10),
    repair_status VARCHAR(20),
    CONSTRAINT fk_sale FOREIGN KEY (sale_id) REFERENCES sales(sale_id)
);

show tables;

select * from category;
select * from products;
select * from stores;
select * from warranty;

## MySQL Business Questions (with Hints & Comments)

---

### 1️ How many product rows does the table contain?
# Why this matters: Basic dataset understanding.
# Hint: Use COUNT(*).

select * from products;
select count(*) from products;

### 2️⃣ How many different products are listed?
# Why this matters: Helps assess product variety.
# Hint: Use COUNT(DISTINCT column_name).

select count(distinct product_name) as unique_product_name
 from products;

### 3️ What is the average price of products?
# Why this matters: Price trend analysis.
# Hint: Use AVG(price).
select avg(price) as average_price from products;

### 4 What is the highest product price?
# Why this matters: Understand max pricing.
# Hint: Use MAX(price).
select max(price) as max_price from products;

### 5️ How many products fall under each category?
# Why this matters: Category distribution for inventory.
# Hint: Use GROUP BY category_id.
select c.category_id, count(p.product_id) from products as p
join category as c
on p.category_id = c.category_id
group by category_id;


### 6️ What is the total quantity sold across all sales?
# Why this matters: Overall demand measurement.
# Hint: Use SUM(quantity).

select * from sales;

select sum(quantity) as total_sold 
from sales;


### 7️ Which category_name earned the highest total price?
# Why this matters: Category performance comparison.
# Hint: Group by category_name → sum price → order by DESC.

select category_name, sum(price) as total_price from category as c
join products as p
on c.category_id = p.category_id
group by category_name ;


### 8️ What are the total sales for each month?
# Why this matters: Useful for monthly performance charts.
# Hint: Use MONTH(date) and GROUP BY.


select month(sale_date) as sales_month,sum(price) as total_sales
from sales as s
join products as p
on s.product_id = p.product_id
group by month(sale_date);

### 9️ What is the revenue generated by each product?
# Why this matters: Product profitability analysis.
# Hint: Group by product_id → sum total_amount.

select p.product_id ,sum(price) as total_sales
from sales as s
join products as p
on s.product_id = p.product_id
group by p.product_id;



### 10️ What is the average customer quantity?
# Why this matters: Customer satisfaction measurement.
# Hint: Use AVG(quantity).

select avg(quantity) as Avg_quantity
 from sales;

